/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Control_Mantenimiento_Estudiante;


/**
 *
 * @author estudiante
 */
public class ManipularEstudiantes extends javax.swing.JFrame {
    
    private Control_Mantenimiento_Estudiante cme;

    Control_Mantenimiento_Estudiante controlEstudiante= new Control_Mantenimiento_Estudiante();
    /**
     * Creates new form ManipularEstudiantes
     */
    
    public ManipularEstudiantes() {
        initComponents();
        cme = new Control_Mantenimiento_Estudiante(this);
        this.gUI_botones2.agregar_eventos(cme);
    }

    public String[] BUSCAR()
    {
        String informacion[]=new String[3];
        informacion[0]=this.jt_nombre.getText();
        informacion[1]=this.jt_carnet.getText();
        informacion[2]=this.jt_correo.getText();
        
        
        return informacion;
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_botones2 = new vista.GUI_botones();
        jPanel1 = new javax.swing.JPanel();
        carnet = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        jt_carnet = new javax.swing.JTextField();
        jt_nombre = new javax.swing.JTextField();
        jt_correo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carnet.setText("Carnet");

        nombre.setText("Nombre");

        correo.setText("Correo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(correo)
                    .addComponent(nombre)
                    .addComponent(carnet))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_carnet)
                    .addComponent(jt_nombre)
                    .addComponent(jt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carnet)
                    .addComponent(jt_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gUI_botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(gUI_botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public int get_codigo_por_fuente(Object obj){
        int dev = 0;
        if(this.jt_carnet.equals(obj)){
            dev = Control_Mantenimiento_Estudiante.CARNET;
        }else if(this.jt_correo.equals(obj)){
            dev = Control_Mantenimiento_Estudiante.CORREO;
        }else if(this.jt_nombre.equals(obj)){
            dev = Control_Mantenimiento_Estudiante.NOMBRE;
        }else{
            dev = this.gUI_botones2.get_codigo_por_fuente(obj);
        }
        
        return dev;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carnet;
    private javax.swing.JLabel correo;
    private vista.GUI_botones gUI_botones2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jt_carnet;
    private javax.swing.JTextField jt_correo;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

    
    public void BUSCAR
    {
            if(jt_carnet.getText().equals(carnet))
                {
                    
                } else 
                
                {

}


